# Generated by Django 5.0.6 on 2024-05-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_lead_email_lead_full_name_lead_notes_lead_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="click",
            name="user_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
