# Generated by Django 5.0.6 on 2024-05-28 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_alter_click_user_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="click",
            name="click_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
